# Use postgres/example user/password credentials
services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./pg16-data:/var/lib/postgresql/data
