services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
      # Using docker in a dockerized Jenkins container
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
