services:
  redis:
    image: redis:7-alpine
    container_name: redis-standalone
    restart: always
    command: [ "redis-server", "--save", '""', "--appendonly", "no" ]
    ports:
      - 127.0.0.1:6379:6379
