# ClickHouse Document: https://clickhouse.yandex/docs/en/
# ClickHouse Docker Hub: https://hub.docker.com/r/yandex/clickhouse-server

version: '3.7'
services:
  clickhouse:
    image: yandex/clickhouse-server
    container_name: clickhouse-server
    restart: always
    ulimits:
      nofile:
        soft: "262144"
        hard: "262144"
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - ./clickhouse-config/metrika.xml:/etc/clickhouse-server/metrika.xml
      - ./clickhouse-config/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse-config/users.xml:/etc/clickhouse-server/users.xml
      - ./clickhouse-data:/var/lib/clickhouse
      - ./clickhouse-log:/var/log/clickhouse-server
