# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:10.4-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
