# https://hub.docker.com/_/mysql
# Use root/example as user/password credentials

services:
  mysql:
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
  adminer:
    image: adminer:4
    restart: always
    ports:
      - 8080:8080