# https://hub.docker.com/_/mysql

# Use root/example as user/password credentials
version: '3.1'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - ./datadir:/var/lib/mysql
