version: '3'

services:
  redis:
    image: redis:5-alpine
    container_name: redis-standalone
    restart: always
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server"]
    ports:
      - 6379:6379
