version: '3'

services:
  redis:
    image: redis:5-alpine
    container_name: redis-standalone
    restart: always
    command: ["redis-server", "--save", '""', "--appendonly", "no"]
    ports:
      - 6379:6379
