version: '3'

services:
  redis:
    image: redis:4-alpine
    restart: always

  postgresql:
    image: postgres:10.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  sentry:
    image: sentry:8.22.0
    restart: always
    depends_on:
      - redis
      - postgresql
    links:
      - redis
      - postgresql
    ports:
      - 9000:9000
    volumes:
      - ./sentry.conf.py:/etc/sentry/sentry.conf.py
    environment:
      SENTRY_REDIS_HOST: redis
      SENTRY_POSTGRES_HOST: postgresql

  sentry_celery_beat:
    image: sentry:8.22.0
    restart: always
    depends_on:
      - redis
      - postgresql
    links:
      - redis
      - postgresql
    volumes:
      - ./sentry.conf.py:/etc/sentry/sentry.conf.py
    environment:
      SENTRY_REDIS_HOST: redis
      SENTRY_POSTGRES_HOST: postgresql
    command: "run cron"

  sentry_celery_worker_1:
    image: sentry:8.22.0
    restart: always
    depends_on:
      - redis
      - postgresql
    links:
      - redis
      - postgresql
    volumes:
      - ./sentry.conf.py:/etc/sentry/sentry.conf.py
    environment:
      SENTRY_REDIS_HOST: redis
      SENTRY_POSTGRES_HOST: postgresql
    command: "run worker"

  sentry_celery_worker_2:
    image: sentry:8.22.0
    restart: always
    depends_on:
      - redis
      - postgresql
    links:
      - redis
      - postgresql
    volumes:
      - ./sentry.conf.py:/etc/sentry/sentry.conf.py
    environment:
      SENTRY_REDIS_HOST: redis
      SENTRY_POSTGRES_HOST: postgresql
    command: "run worker"
